name: draw.io
services:
  app:
    image: jgraph/drawio:21.5.2
    restart: unless-stopped
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: draw.io (formerly Diagramly) is free online diagram software. You can use it as a flowchart maker, network diagram software, to create UML online, as an ER diagram tool, to design database schema, to build BPMN online, as a circuit diagram maker, and more. draw.io can import .vsdx, Gliffy™ and Lucidchart™ files.
  tagline:
    en_us: Draw.io (formerly Diagramly) Is Free Online Diagram Software. You Can Use It As A Flowchart Maker, Network Diagram Software, To Create Uml Online, As An Er Diagram Tool, To Design Database Schema, To Build Bpmn Online, As A Circuit Diagram Maker, And More. Draw.io Can Import .vsdx, Gliffy™ And Lucidchart™ Files.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/qwerty00007/portainer_templates/master/Images/draw.io.png
  thumbnail: https://raw.githubusercontent.com/qwerty00007/portainer_templates/master/Images/draw.io.png
  title:
    en_us: Draw.io
  category: Management Utility Server
  port_map: '8080'
