name: statping
services:
  app:
    image: statping/statping:v0.90.74
    restart: always
    environment: {}
    x-casaos:
      envs: []
    ports:
      - target: 4040
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/Config/statping
        target: /app
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: An easy to use Status Page for your websites and applications. Statping will automatically fetch the application and render a beautiful status page with tons of features for you to build an even better status page.
  tagline:
    en_us: An Easy To Use Status Page For Your Websites And Applications. Statping Will Automatically Fetch The Application And Render A Beautiful Status Page With Tons Of Features For You To Build An Even Better Status Page.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/statping.png
  thumbnail: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/statping.png
  title:
    en_us: Statping
  category: Network
  port_map: '4040'
