name: 2fauth
services:
  app:
    image: 2fauth/2fauth:latest
    container_name: 2fauth
    restart: unless-stopped
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      
      # VITAL: This key is used to encrypt sensitive data in the database.
      - APP_KEY=$APP_KEY
      
      # Site Owner Email
      - SITE_OWNER=blissoskala@gmail.com
      
      - APP_ENV=production
      - AUTHENTICATION_GUARD=web-guard

    volumes:
      # Persistent storage for the SQLite database and configuration
      - type: bind
        source: /DATA/AppData/2fauth/2fauth
        target: /2fauth
        
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: app
  description:
    en_us: 2FAuth is a self-hosted, web-based alternative to OTP generators like Google Authenticator. It allows you to securely manage your 2FA accounts and generate codes from your desktop or mobile browser.
  tagline:
    en_us: Self-hosted Two-Factor Authentication Manager.
  developer: 2FAuth
  author: Bubka/CasaOS Community
  icon: https://raw.githubusercontent.com/Bubka/2FAuth/master/public/logo.png
  category: Utilities
  port_map: 8000
  title:
    en_us: 2FAuth
  envs:
    - name: TZ
      label: Timezone
      value: Europe/London
      type: select
    - name: APP_KEY
      label: Application Security Key (32-char hex)
      description: A unique, 32-character hexadecimal key required for data encryption. **DO NOT LOSE THIS!**
      value: "replace_with_a_secure_32_char_key" 
      type: text
    - name: SITE_OWNER
      label: Site Owner Email
      description: The email of the primary administrator for the application.
      value: "blissoskala@gmail.com"
      type: text