name: homebridge
services:
  app:
    image: oznu/homebridge:2023-01-08
    restart: unless-stopped
    environment:
      PGID: $PGID
      PUID: $PUID
      HOMEBRIDGE_CONFIG_UI: ''
      HOMEBRIDGE_CONFIG_UI_PORT: ''
      TZ: $TZ
    x-casaos:
      envs:
        - container: PGID
          description:
            en_us: ''
        - container: PUID
          description:
            en_us: ''
        - container: HOMEBRIDGE_CONFIG_UI
          description:
            en_us: ''
        - container: HOMEBRIDGE_CONFIG_UI_PORT
          description:
            en_us: ''
        - container: TZ
          description:
            en_us: ''
    volumes:
      - type: bind
        source: /DATA/AppData/Config/homebridge
        target: /homebridge
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Homebridge allows you to integrate with smart home devices that do not natively support HomeKit. There are over 2,000 Homebridge plugins supporting thousands of different smart accessories.
  tagline:
    en_us: Homebridge Allows You To Integrate With Smart Home Devices That Do Not Natively Support Homekit. There Are Over 2,000 Homebridge Plugins Supporting Thousands Of Different Smart Accessories.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/homebridge.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/homebridge.png
  title:
    en_us: Homebridge
  category: HomeAutomation
