name: picturesque_kaity
services:
  jellyfin:
    cpu_shares: 90
    command: []
    container_name: jellyfin
    deploy:
      resources:
        limits:
          memory: 16658272256
        reservations:
          devices: []
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=Etc/UTC
    image: jellyfin/jellyfin:latest
    labels:
      icon: https://icon.casaos.io/main/all/jellyfin.png
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
      - target: 8920
        published: "8920"
        protocol: tcp
      - target: 7359
        published: "7359"
        protocol: udp
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /tmp/casaos-compose-app-1523647174/cache
        target: /cache
      - type: bind
        source: /DATA/Media
        target: /media
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/jellyfin.png
  index: /
  is_uncontrolled: false
  port_map: "8096"
  scheme: http
  store_app_id: picturesque_kaity
  title:
    custom: ""
    en_us: jellyfin
